/* 
 * Copyright 2017 José A. Pacheco Ondoño - joanpaon@gmail.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.japo.java.views;

import java.awt.Color;
import java.util.Properties;
import org.japo.java.controllers.Controller;
import org.japo.java.libraries.UtilesApp;
import org.japo.java.libraries.UtilesValidacion;
import org.japo.java.models.Model;

/**
 *
 * @author José A. Pacheco Ondoño - joanpaon@gmail.com
 */
public class View extends javax.swing.JFrame {
    // Propiedades Vista
    public static final String PRP_PUERTO_BLOQUEO = "puerto_bloqueo";
    public static final String PRP_LOOK_AND_FEEL = "lnf";
    public static final String PRP_RUTA_FAVICON = "ruta_favicon";

    // Fichero Propiedades Vista
    public static final String FICHERO = "view.properties";

    // Referencias
    private Model model;
    private Controller control;
    private Properties prpView;

    // Constructor
    public View() {
        // Inicializacion Anterior
        initBefore();

        // Creación Vista
        initComponents();

        // Inicializacion Posterior
        initAfter();
    }

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        lblLink = new javax.swing.JLabel();
        txfLink = new javax.swing.JTextField();
        btnLink = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        txfUser = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txfPass = new javax.swing.JTextField();
        cbxPass = new javax.swing.JCheckBox();
        lblCode = new javax.swing.JLabel();
        txfCode = new javax.swing.JTextField();
        pnlControles = new javax.swing.JPanel();
        btnImportar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shop Assistant");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Promoción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        lblLink.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblLink.setText("Enlace");

        txfLink.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txfLink.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfLinkFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfLinkFocusLost(evt);
            }
        });
        txfLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfLinkActionPerformed(evt);
            }
        });

        btnLink.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLink.setText(">");
        btnLink.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnLink.setMaximumSize(new java.awt.Dimension(40, 40));
        btnLink.setMinimumSize(new java.awt.Dimension(40, 40));
        btnLink.setOpaque(false);
        btnLink.setPreferredSize(new java.awt.Dimension(40, 40));
        btnLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinkActionPerformed(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUser.setText("Usuario");

        txfUser.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txfUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfUserFocusLost(evt);
            }
        });
        txfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUserActionPerformed(evt);
            }
        });

        lblPass.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPass.setText("Contraseña");

        txfPass.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txfPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfPassFocusLost(evt);
            }
        });
        txfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPassActionPerformed(evt);
            }
        });

        cbxPass.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        cbxPass.setSelected(true);
        cbxPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cbxPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbxPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPassActionPerformed(evt);
            }
        });

        lblCode.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblCode.setText("Código");

        txfCode.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txfCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfCodeFocusLost(evt);
            }
        });
        txfCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLink)
                    .addComponent(lblUser)
                    .addComponent(lblPass)
                    .addComponent(lblCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfLink, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txfUser)
                    .addComponent(txfCode))
                .addContainerGap())
        );

        pnlDatosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCode, lblLink, lblPass, lblUser});

        pnlDatosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLink, cbxPass});

        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLink)
                    .addComponent(txfLink, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblUser)
                    .addComponent(txfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPass)
                    .addComponent(txfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPass))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCode)
                    .addComponent(txfCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLink, lblCode, lblLink, lblPass, lblUser, txfLink});

        pnlDatosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxPass, txfPass});

        pnlControles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        btnImportar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnImportar.setText("Importar");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        btnExportar.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlesLayout = new javax.swing.GroupLayout(pnlControles);
        pnlControles.setLayout(pnlControlesLayout);
        pnlControlesLayout.setHorizontalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlesLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        pnlControlesLayout.setVerticalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportar)
                    .addComponent(btnExportar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        control.procesarCierreVista(evt);
    }//GEN-LAST:event_formWindowClosing

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        control.procesarImportacion(evt);
    }//GEN-LAST:event_btnImportarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        control.procesarExportacion(evt);
    }//GEN-LAST:event_btnExportarActionPerformed

    private void txfLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfLinkActionPerformed
        txfUser.requestFocus();
    }//GEN-LAST:event_txfLinkActionPerformed

    private void txfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUserActionPerformed
        txfPass.requestFocus();
    }//GEN-LAST:event_txfUserActionPerformed

    private void txfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPassActionPerformed
        txfCode.requestFocus();
    }//GEN-LAST:event_txfPassActionPerformed

    private void txfCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCodeActionPerformed
        btnExportar.requestFocus();
    }//GEN-LAST:event_txfCodeActionPerformed

    private void txfLinkFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfLinkFocusGained
        txfLink.setForeground(Color.BLACK);
        txfLink.setBackground(Color.CYAN);
    }//GEN-LAST:event_txfLinkFocusGained

    private void txfUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfUserFocusGained
        txfUser.setForeground(Color.BLACK);
        txfUser.setBackground(Color.CYAN);
    }//GEN-LAST:event_txfUserFocusGained

    private void txfPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfPassFocusGained
        txfPass.setForeground(Color.BLACK);
        txfPass.setBackground(Color.CYAN);
    }//GEN-LAST:event_txfPassFocusGained

    private void txfCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfCodeFocusGained
        txfCode.setForeground(Color.BLACK);
        txfCode.setBackground(Color.CYAN);
    }//GEN-LAST:event_txfCodeFocusGained

    private void txfLinkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfLinkFocusLost
        UtilesValidacion.validarCampoTexto(txfLink, Model.ER_LINK, "?");
        txfLink.setBackground(Color.WHITE);
    }//GEN-LAST:event_txfLinkFocusLost

    private void txfUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfUserFocusLost
        UtilesValidacion.validarCampoTexto(txfUser, Model.ER_USER, "?");
        txfUser.setBackground(Color.WHITE);
    }//GEN-LAST:event_txfUserFocusLost

    private void txfPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfPassFocusLost
        UtilesValidacion.validarCampoTexto(txfPass, Model.ER_PASS, "?");
        txfPass.setBackground(Color.WHITE);
    }//GEN-LAST:event_txfPassFocusLost

    private void txfCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfCodeFocusLost
        UtilesValidacion.validarCampoTexto(txfCode, Model.ER_CODE, "");
        txfCode.setBackground(Color.WHITE);
    }//GEN-LAST:event_txfCodeFocusLost

    private void btnLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinkActionPerformed
        control.lanzarNavegador(txfLink.getText());
    }//GEN-LAST:event_btnLinkActionPerformed

    private void cbxPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPassActionPerformed
        control.procesarPassword(evt);
    }//GEN-LAST:event_cbxPassActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnImportar;
    private javax.swing.JButton btnLink;
    public javax.swing.JCheckBox cbxPass;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblLink;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlControles;
    private javax.swing.JPanel pnlDatos;
    public javax.swing.JTextField txfCode;
    public javax.swing.JTextField txfLink;
    public javax.swing.JTextField txfPass;
    public javax.swing.JTextField txfUser;
    // End of variables declaration//GEN-END:variables

    // Inicializacion Anterior
    private void initBefore() {
        // Crear Modelo
        model = new Model();

        // Crear Controlador
        control = new Controller(model, this);

        // Cargar Propiedades Vista
        prpView = UtilesApp.cargarPropiedades(FICHERO);

        // Restaurar Estado
        control.restaurarEstadoVista(this, prpView);

        // Otras inicializaciones
    }

    // Inicializacion Posterior
    private void initAfter() {
        // Modelo > Vista
//        control.sincronizarModeloVista(model, this);

        // Enfocar Control Inicial
        btnImportar.requestFocus();

        // Otras inicializaciones
    }
}
